package com.automate.controller;

public enum Algorithm {
    MINIMISATION_B , MINIMISATION_H , DERTIMINISATION , EP_DERTIMINISATION , COMPLEMENTAIRE , COMPLETION , MIROIR_AFD, MIROIR_AFN
    ,RECONNAISSANCE_AFD , RECONNAISSANCE_AFN
}
